-- V1__initial_schema.sql

CREATE TABLE public.users (
    id            INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username      TEXT NOT NULL UNIQUE,
    first_name    TEXT NOT NULL,
    last_name     TEXT NOT NULL,
    email         TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.patient (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT patient_pk PRIMARY KEY,
    mrn             TEXT NOT NULL,
    last_name       TEXT,
    first_name      TEXT,
    middle_name     TEXT,
    sex             TEXT,
    date_of_birth   TEXT,
    suffix          TEXT,
    prefix          TEXT,
    created_at      TEXT,
    last_updated_at TEXT
);

CREATE TABLE public.study (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT study_pk PRIMARY KEY,
    patient_id      INTEGER REFERENCES public.patient(id), -- Added explicit reference
    studyid         TEXT,
    accn_num        TEXT,
    study_uid       TEXT,
    study_date      DATE,
    study_year      INTEGER,
    modality        TEXT,
    description     TEXT,
    created_at      TIMESTAMP,
    last_updated_at TIMESTAMP
);

CREATE TABLE public.series (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT series_pk PRIMARY KEY,
    study_id           INTEGER NOT NULL CONSTRAINT series_study_id_fk REFERENCES public.study(id),
    series_uid         TEXT,
    series_number      INTEGER,
    modality           TEXT,
    body_part_examined TEXT,
    description        TEXT,
    study_year         INTEGER,
    created_at         TIMESTAMP,
    last_updated_at    TIMESTAMP
);

CREATE TABLE public.image (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT image_pk PRIMARY KEY,
    series_id           INTEGER CONSTRAINT image_series_id_fk REFERENCES public.series(id),
    study_id            INTEGER REFERENCES public.study(id), -- Added explicit reference
    image_uid           TEXT,
    instance_number     INTEGER,
    image_position      INTEGER,
    rows                INTEGER,
    columns             INTEGER,
    transfer_syntax_uid TEXT,
    study_year          INTEGER,
    modality            TEXT,
    image_url           TEXT,
    created_at          TIMESTAMP,
    last_updated_at     TIMESTAMP
);

-- Indices for performance (Essential for PACS search)
CREATE INDEX idx_patient_mrn ON public.patient(mrn);
CREATE INDEX idx_study_uid ON public.study(study_uid);
CREATE INDEX idx_series_study_id ON public.series(study_id);
CREATE INDEX idx_image_series_id ON public.image(series_id);