create table public.employees
(
    emp_id     bigint generated by default as identity (cache 20)
        primary key,
    first_name varchar(50),
    last_name  varchar(50),
    salary     numeric(10, 2),
    dept_id    bigint,
    branch_id  bigint,
    manager_id bigint,
    notes      text,
    json_data  text
);
