drop table public.employees_test2;


create table public.test
(
    id     bigint generated by default as identity (cache 20)
        primary key,
   col1  text
);

insert into public.test ('row 1');

insert into public.test ('row 2');

insert into public.test ('row 3');
