steps:
  # 1. Start an Ephemeral PostgreSQL Database
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Start Temporary DB'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker run -d --name temp-postgres \
          -e POSTGRES_PASSWORD=password \
          -e POSTGRES_DB=pacs_test \
          -p 5432:5432 \
          postgres:17-alpine
        
        # Give Postgres a few seconds to initialize
        echo "Waiting for Postgres to start..."
        sleep 10

  # 2. Build the Migration Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Migration Image'
    args: ['build', '-t', 'pacs-migrations:test', '-f', 'backend/migrations/Dockerfile.flyway', 'backend/.']

  # 3. DRY RUN: Test Migrations against Temporary DB
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Test Migrations'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker run --network=host \
          -e FLYWAY_URL=jdbc:postgresql://localhost:5432/pacs_test \
          -e FLYWAY_USER=postgres \
          -e FLYWAY_PASSWORD=password \
          pacs-migrations:test migrate
    # If this fails, the PR fails!

  # 4. Build App Images (Checking for compilation/syntax errors)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Test Build Backend'
    args: ['build', '-t', 'test-backend', './backend']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Test Build Frontend'
    args: ['build', '-t', 'test-ui', './frontend']

options:
#  logging: CLOUD_LOGGING_ONLY

# Note: We do NOT push images or touch GKE here.