steps:
  # 1. Build and Push (Standard Steps)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build, Push Application and Database'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t ${_REGION_SHORT}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/pacs-migrations:${SHORT_SHA} -f backend/migrations/Dockerfile.flyway backend/.
        docker build -t ${_REGION_SHORT}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/pacs-backend:${SHORT_SHA} backend/.
        docker build -t ${_REGION_SHORT}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/pacs-ui:${SHORT_SHA} frontend/.
        
        docker push ${_REGION_SHORT}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/pacs-migrations:${SHORT_SHA}
        docker push ${_REGION_SHORT}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/pacs-backend:${SHORT_SHA}
        docker push ${_REGION_SHORT}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/pacs-ui:${SHORT_SHA}

  # 2. Database Migration with Polling Logic
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Migrate DB'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud components install gke-gcloud-auth-plugin --quiet
        gcloud container clusters get-credentials ${_CLUSTER_NAME} --zone ${_REGION} --project ${PROJECT_ID}
        
        # Ensure fresh start
        kubectl delete job pacs-migration-job --ignore-not-found
        
        # Apply the migration job
        sed "s|image: .*pacs-migrations:.*|image: ${_REGION_SHORT}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/pacs-migrations:${SHORT_SHA}|g" k8s/flyway-job.yaml > flyway-run.yaml
        kubectl apply -f flyway-run.yaml
        
        echo "Checking migration status..."
        # Loop 12 times (max 60 seconds) to check status manually
        for i in {1..12}; do
          # Check for success
          SUCCESS=$$(kubectl get job pacs-migration-job -o jsonpath='{.status.succeeded}' 2>/dev/null)
          if [ "$$SUCCESS" == "1" ]; then
            echo "Migration SUCCESSFUL (Version 9+). Moving to deploy..."
            exit 0
          fi
          
          # Check for failure
          FAILED=$$(kubectl get job pacs-migration-job -o jsonpath='{.status.failed}' 2>/dev/null)
          if [ "$$FAILED" == "1" ]; then
            echo "MIGRATION FAILED! Fetching logs..."
            kubectl logs -l job-name=pacs-migration-job -c flyway
            exit 1
          fi
          
          echo "Still processing... (attempt $$i/12)"
          sleep 5
        done

        echo "ERROR: Migration timed out after 60 seconds!"
        exit 1
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
      - 'USE_GKE_GCLOUD_AUTH_PLUGIN=True'

  # 3. Deploy Updates
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy Updates'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials ${_CLUSTER_NAME} --zone ${_REGION} --project ${PROJECT_ID}
        kubectl set image deployment/pacs-backend pacs-api=${_REGION_SHORT}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/pacs-backend:${SHORT_SHA}
        kubectl set image deployment/pacs-frontend pacs-ui=${_REGION_SHORT}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/pacs-ui:${SHORT_SHA}
        kubectl rollout status deployment/pacs-backend
        kubectl rollout status deployment/pacs-frontend
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
      - 'USE_GKE_GCLOUD_AUTH_PLUGIN=True'

substitutions:
  _REGION: us-central1-a
  _REGION_SHORT: us-central1
  _REPO_NAME: pacs-repo
  _CLUSTER_NAME: mwakilishi-cluster

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: 'ALLOW_LOOSE'