services:
  db:
    image: postgres:17-alpine
    container_name: pacs_testdb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pacs
    ports:
      - "5435:5432"
    volumes:
      - pacs_db_data:/var/lib/postgresql/data

  pacs-backend-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/pacs
    depends_on:
      - db

  pacs-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://pacs-backend-service:8000
    depends_on:
      - pacs-backend-service

volumes:
  pacs_db_data: